spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.batch_size: 100
        default_fetch_size: 100
        order_inserts: true
        order_updates: true
      javax:
        persistence:
          sharedCache.mode: ALL
---
spring:
  config:
    activate:
      on-profile: "db-local"

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    database: H2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;
    username: sa
    password:
---
spring:
  config:
    activate:
      on-profile: "db-dev"

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(r7D689EMB0Ipo6ZXJTTqXyIFR50a7Hp3EzWJvkTkuqQGHFZcpDGzR3HjfO3qxfs8GepM+Mg3WbKrAPaq/R60dJSe+02jAyWHDVQF5Im6H8fdaQpovs7yaV8SlXjrdi3+vCDHNN13QRI=)
    username: ENC(xmsrXLmgjOeAgV0Q+cS/WOdQ7uvGXX6L)
    password: ENC(HdMOQkImCi1MgeZgKxtxg3Aan93d8xw9IZDNXXxvFuQ=)